apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    purpose: etcd-backup
    config.example.com/name: etcd-backup
    config.example.com/component: cronjob
  name: cronjob-etcd-backup
  namespace: etcd-backup 
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          activeDeadlineSeconds: 200
          initContainers:
          - command:
            - /usr/local/bin/etcd-backup.sh
            image: quay.io/openshift/origin-etcd:4.3.0
            imagePullPolicy: IfNotPresent
            name: etcd-backup
            resources:
              requests:
                cpu: 300m
                memory: 250Mi
            securityContext:
              privileged: true
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: FallbackToLogsOnError
            volumeMounts:
            - mountPath: /etc/ssl/etcd/
              name: certs
            - mountPath: /etc/etcd/
              name: conf
            - mountPath: /etc/kubernetes/
              name: kubeconfig
            - mountPath: /usr/local/bin
              name: scripts
            - mountPath: /etcd-backup
              name: etcd-backup
            - mountPath: /usr/local/bin/etcd-backup.sh
              name: etcd-backup-scripts
              subPath: etcd-backup.sh
            - mountPath: /usr/local/bin/etcd-snapshot-backup-disconnected.sh
              name: etcd-backup-scripts
              subPath: etcd-snapshot-backup-disconnected.sh
          containers:
          ##AWSCLI
          - name: kubectl-aws
            image: expert360/kubectl-awscli:v1.11.2
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-s3-key
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-s3-access-key
                  key: aws-secret-access-key
            command: [ "/bin/bash", "-c", "aws s3 sync s3://my-bucket/ /data/backup" ]
            volumeMounts:
            - name: etcd-backup
              mountPath: /data/backup
          nodeSelector:
            node-role.kubernetes.io/master: ""
          dnsPolicy: ClusterFirst
          securityContext:
            runAsuser: 0
          serviceAccount: etcd-backup
          serviceAccountName: etcd-backup
          hostNetwork: true
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          tolerations:
          - effect: NoSchedule
            operator: Exists
          - effect: NoExecute
            operator: Exists
          volumes:
          - name: certs
            hostPath:
              path: /etc/kubernetes/static-pod-resources/etcd-member
              type: ""
          - name: conf
            hostPath:
              path: /etc/etcd
              type: ""
          - name: kubeconfig
            hostPath:
              path: /etc/kubernetes
              type: ""
          - name: scripts
            hostPath:
              path: /usr/local/bin
              type: ""
          - name: etcd-backup
            persistentVolumeClaim:
              claimName: etcd-backup
          - name: etcd-backup-scripts
            configMap:
              name: etcd-backup 
              defaultMode: 0755
  schedule: '*/30 * * * *'
  startingDeadlineSeconds: 200
  successfulJobsHistoryLimit: 5
